Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
   
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/post/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="index"),
    path('post-detail/<int:id>', views.post_details, name="post-details"),
    path('create-post', views.create_post, name="create-post"),
    path('register', views.registerUser, name="register"),
    path('logout', views.logout,name="logout" ),
]

Blog/post/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
class BlogPost(models.Model):
    title = models.CharField(max_length=254, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    content = models.TextField()
    image = models.ImageField(upload_to="posts/")
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)

    def __str__(self):
        return self.title
# Create your models here.

Blog/post/forms.py
from django import forms
from django.forms.widgets import TextInput
from .models import Category , BlogPost

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

# class PostForm(forms.ModelForm):
#     class Meta:
#         model = BlogPost
#         fields = '__all__'


class PostForm(forms.ModelForm):
    title = forms.CharField(
        max_length=200,
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.all().filter(is_active=True),
        widget=forms.Select(
            attrs={
                'class': 'form-control',
            }
        )
    )

    content = forms.CharField(
        required=True,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows':'3'
            }
        )
    )

    image = forms.ImageField(
        required=True,
        widget=forms.FileInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    is_active = forms.BooleanField(required=False,initial=True)
    is_featured = forms.BooleanField(required=False,initial=False)

    class Meta:
        model = BlogPost
        fields = ['title','category', 'content', 'image','is_featured', 'is_active']

Blog/post/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import BlogPost, Category
from .forms import PostForm
from django.contrib import messages
from django.shortcuts import redirect, render, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages

# def index(request):
#     data = {
#         'name' : "Aasish Ghising",
#         'address' : "Pokhara",
#     }
#     return HttpResponse(data)

# def index(request):
#     return render(request, 'post/index.html')

def index(request):
  posts = BlogPost.objects.all().filter(is_active=True)
  categories = Category.objects.all()

  context = {
    'posts':posts,
    'categories':categories
  }
  return render(request, 'post/index.html', context)

def post_details(request, id):
  post = BlogPost.objects.get(id=id)
  context = {
    'post':post,
  }
  return render(request, 'post/post-details.html', context)

def create_post(request):
    form = PostForm()
    categories = Category.objects.all();

    if request.method == "POST":
        title = request.POST.get('title')
        if title == "":
            messages.error(request, "Title field is required.")
            return HttpResponseRedirect('/create-post')
        category = Category.objects.get(id=request.POST.get('category'))   
        content = request.POST.get('content')
        if content == "":
            messages.error(request, "Content field is required.")
            return HttpResponseRedirect('/create-post')
        image = request.FILES.get('image')
        if image == "":
            messages.error(request, "Image field is required.")
            return HttpResponseRedirect('/create-post')
        is_active = request.POST.get('is_active')
        is_featured = request.POST.get('is_featured')

        if is_active == "on":
            is_active = True
        else:
            is_active = False

        if is_featured == "on":
            is_featured = True
        else:
            is_featured = False

        post = BlogPost.objects.create(
            title = title,
            category = category,
            author = request.user,
            content = content,
            image = image,
            is_active = is_active,
            is_featured = is_featured,
        )
        post.save()
        messages.success(request, f"{title} is Created Successfully.")
        return HttpResponseRedirect('/create-post')

    context = {
        'form':form,
        'categories':categories,
    }
    return render(request, 'post/create-post.html', context)


def registerUser(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        if request.method == "POST":
            email = request.POST.get('email')
            username = request.POST.get('username')
            password = request.POST.get('password')
            password2 = request.POST.get('password2')

            if username and email and password:
                if password == password2:
                    user = User.objecte.create(
                        email=email, 
                        username = username, 
                        password = password)
                    user.save()
                    login(request,user)
                    return redirect('/')
                else:
                    messages.error(request, "The two password fields didn'/t match.")
                    return HttpResponseRedirect('/register')
            else:
              messages.error(request, "All fields are required.")
              return HttpResponseRedirect('/register')
    return render(request, 'post/register.html')

def logout_result(request):
    logout(request)
    return HttpResponseRedirect('/register.html')

Blog/post/templates/post/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title%}{% endblock title%} | Django Blog</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
        <style>
            body {
                overflow-x: hidden;
            }

            .blog-footer {
                margin-top: 20px;
                padding: 1rem 0;
                color: #999;
                text-align: center;
                background-color: #f9f9f9;
                border-top: .05rem solid #e5e5e5;
            }

            .blog-footer p:last-child {
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <div class="container mt-3">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded justify-content-between">
                <a class="navbar-brand" href="/">MyBlog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item ">
                            <a class="nav-link" href="#">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact us </a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Welcome Back {{user.username|capfirst}}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Profile</a>
                                <a class="dropdown-item" href="#">Create Blog</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Logout</a>
                            </div>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">Login </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "/logout" %}">Logout </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "/register" %}">Register</a>
                        </li>
                        {% endif %}
                    </ul>
                    <form class="form-inline my-2 my-lg-0" action="/" method="GET">
                        <input required class="form-control mr-sm-2" name="q" type="search" placeholder="Search..."
                            aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </nav>
        </div>
        {% block body%} {% endblock body %}
        <div class="container mt-3">
            <footer class="blog-footer rounded">
                <p>Blog template built for <a href="#">Bootstrap</a>.</p>
                <p>
                    <a href="#">Back to top</a>
                </p>
            </footer>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    </body>
</html>

Blog/post/templates/post/create-post.html
<form class="needs-validation" enctype="multipart/form-data" action="{% url 'create-post' %}" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-12 mb-3">
            <label for="firstName">Title</label>
            {{form.title}}
        </div>
    </div>
    <div class="mb-3">
        <label for="lastName">Category</label>
        <select name="category" id="category" class="form-control">
            {% for category in categories %}
            <option value="{{category.id}}">{{category.name}}</option>
            {% endfor %}
        </select>

    </div>
    <div class="mb-3">
        <label for="email">Content </label>
        {{form.content}}
    </div>
    <div class="mb-3">
        <label for="email">Feature Image </label>
        {{form.image}}
    </div>
    <div class="mb-3">
        <label for="id_is_active">Is Active ? </label>
        {{form.is_active}}
    </div>
    <div class="mb-3">
        <label for="id_is_featured">Is Featured Post ? </label>
        {{form.is_featured}}
    </div>
    <div class="row d-flex justify-content-end">
        <div class="col-md-4 ml-0 ">
            <button class="btn btn-success btn-lg btn-block" type="submit">Create Post</button>
        </div>
    </div>
</form>

Blog/post/templates/post/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title> Home  | Django Blog</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
        <style>
            body {
                overflow-x: hidden;
            }

            .blog-footer {
                margin-top: 20px;
                padding: 1rem 0;
                color: #999;
                text-align: center;
                background-color: #f9f9f9;
                border-top: .05rem solid #e5e5e5;
            }

            .blog-footer p:last-child {
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <div class="container mt-3">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded justify-content-between">
                <a class="navbar-brand" href="/">MyBlog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item ">
                            <a class="nav-link" href="#">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact us </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="/login">Login </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/register">Register </a>
                        </li>
                        


                    </ul>
                    <form class="form-inline my-2 my-lg-0" action="/" method="GET">
                        <input required class="form-control mr-sm-2" name="q" type="search" placeholder="Search..."
                            aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </nav>
        </div>

<div class="container">
    <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-start">

            <a class="p-2 text-info font-weight-bold" href="?category=technology">Technology</a>

            <a class="p-2 text-info font-weight-bold" href="?category=politics">Politics</a>

            <a class="p-2 text-info font-weight-bold" href="?category=lorem">Lorem</a>

            {{BlogPost}}
                <br>
            {{Categories}}

            

        </nav>
    </div>






    <div class="row mb-2">


        {% for post in posts %}

        <div class="col-md-6">
            <div class="card flex-md-row mb-4 box-shadow h-md-250">
                <div class="row">
                    <div class="col-lg-8 col-md-12 col-sm-12">
                        <div class="card-body d-flex flex-column align-items-start">
                            <strong class="d-inline-block mb-2 text-success">{{post.category}}</strong>
                            <h3 class="mb-0">
                                <a class="text-dark" href="{% url "post-details" post.id %}">
                                    {{post.title}}
                                </a>
                            </h3>
                            <div class="mb-1 text-muted">
                                {{post.created_at}}
                            </div>
                            <p class="card-text mb-auto">
                                {{post.content}}
                            </p>
                            <a href="/post/where-can-i-get-some" class="mt-2 text-warning">Continue
                                reading...</a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12 col-sm-12">
                        <img class="img-fluid rounded h-100 w-100" src="{{post.image.url}}" alt="{{post.title}}">
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}




    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination">

            <li class="page-item disabled"><a class="page-link disabled" href="#">Previous</a></li>

            <li class="page-item"><a class="page-link" href="#">1 of
                    2</a></li>

            <li class="page-item"><a class="page-link" href="?page=2">Next</a>
            </li>

        </ul>
    </nav>

</div>

        <div class="container mt-3">
            <footer class="blog-footer rounded">
                <p>Blog template built for <a href="#">Bootstrap</a>.</p>
                <p>
                    <a href="#">Back to top</a>
                </p>
            </footer>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    </body>
</html>

Blog/post/templates/post/post-details.html
<h1> Title: {{post.title}} </h1>

<p> Date : {{post.created_at}} </p>

<p> {{post.content}} </p>

Blog/post/templates/post/register.html
{% extends 'post/base.html' %}

{% block title %} Register {% endblock title %}
{% block body %}
<div class="row d-flex justify-content-center">
    <div class="col-md-4">
        {% if messages %}
        {% for message in messages %}
        <div class="mt-4 alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}
            alert-dismissible" role="alert">
            <div id="form_errors">
                <strong>{{message}}</strong>
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
        <form class="form-signin mt-3 mb-4" method="POST" action="{% url 'register' %}">
            {% csrf_token %}
            <div class="form-label-group">
                <label for="inputEmail">Email</label>
                <input type="email" id="inputEmail" class="form-control" placeholder="Email..." autofocus name="email"
                    autocomplete="off">
            </div>
            <div class="form-label-group">
                <label for="inputPassword">Username</label>
                <input type="text" id="inputUsername" class="form-control" placeholder="Username..." name="username">
            </div>
            <div class="form-label-group">
                <label for="inputPassword">Password</label>
                <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password">
            </div>
            <div class="form-label-group">
                <label for="inputPassword">Confirm Password</label>
                <input type="password" id="inputConfirmPassword" class="form-control" placeholder="Confirm Password"
                    name="password2">
            </div>
            <div class="checkbox mb-3">
                <a href="{% url 'login'%}">Already Registered?</a>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
        </form>
    </div>
</div>

{% endblock %}